### ISSUE TITLE
Indentation count lost after comment in code (Again)

### ISSUE THREAD

**Issue by jnvsor** [FriendsOfPHP/PHP-CS-Fixer#1904]
It looks like bug #774 is back

**Before:**

```php
<?php

function a()
{
      //test
      echo 'Ahem';
}
```
**Command:**

```
$ php-cs-fixer -V
PHP CS Fixer version 1.11.2 by Fabien Potencier
$ php-cs-fixer fix -v test.php
.
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Fixed all files in 0.038 seconds, 4.000 MB memory used
```
**After:**

```php
<?php

function a()
{
    //test
      echo 'Ahem';
}
```

**Comment by SpacePossum** [comment]
The first indent fix (i.e. to 4 spaces) looks OK, the `echo`-line however is not touched.
I think the bug is not back; I think it was never solved in the 1.x line since the comment with linebreak transformer was added on `master`.
You could try out the master branch or help out on the 1.x :)

**Comment by jnvsor** [comment]
> PHP CS Fixer version 2.0-DEV by Fabien Potencier and Dariusz Ruminski

Still happens in b86dd31

**Comment by jnvsor** [comment]
Still happens in 13a21d85789f4e6534610722842019b864980bec (And 1.12 too)

**Comment by SpacePossum** [comment]
yes, see also https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2176
it seems nobody found time to fix this

**Comment by keradus** [comment]
closing as duplicate.
@jnvsor do you want to send a fix ?

**Comment by jnvsor** [comment]
@keradus Is there a "Working on php-cs-fixer for dummies" guide? My go to for debugging is `echo` but this likes to error whenever I output anything

**Comment by keradus** [comment]
there is a cookbook, but it's rather for creating new fixer, not fixing a bug.
I would suggest o add failing case to utests and then fix the fixer class
