### ISSUE TITLE
Return type declaration gets "invalid file syntax"

### ISSUE THREAD

**Issue by rhagni** [FriendsOfPHP/PHP-CS-Fixer#2226]
Hello!

I'm having a trouble because I'm using [return type declaration](http://php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration) and this give me "invalid file syntax" when I check my files.

e.g.:  

```
C:\> php7 C:\lib\php-cs-fixer.phar fix --level=psr2 --verbose A.php
I
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Fixed all files in 2.418 seconds, 6.000 MB memory used
```

A.php:
```php
<?php

class A
{
    protected $value;
    
    public function get(): integer
    {
        return $this->value;
    }
}
```

Native PHP 7 syntax checker don't gimme problem:
```
C:\> php7 -l A.php
No syntax errors detected in A.php
```

(Sorry for my bad english)

**Comment by rhagni** [comment]
Additional info:

```
C:\> php7 --version
PHP 7.0.10 (cli) (built: Aug 18 2016 09:48:53) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

```
C:\> php7 C:\lib\php-cs-fixer.phar --version
PHP CS Fixer version 1.12.2 by Fabien Potencier and Dariusz Ruminski (baa7112)
```

**Comment by keradus** [comment]
Please, could you check dev-master version ?

**Comment by rhagni** [comment]
```
C:\> composer require friendsofphp/php-cs-fixer dev-master
C:\> setlocal DISABLEDELAYEDEXPANSION
C:\> php7 vendor\friendsofphp\php-cs-fixer\php-cs-fixer fix --level=psr2 --verbose A.php
.
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error

Fixed all files in 0.009 seconds, 6.000 MB memory used
```

Thank you so much @keradus, you saved me 😊

**Comment by keradus** [comment]
`--level=psr2` is not working on  master branch, but the PSR2 is used by default ;)
awesome, on master branch we have more support for PHP7 syntax

**Comment by keradus** [comment]
I think it's resolved now, could we close it ?

**Comment by rhagni** [comment]
@keradus Yeess thanks again, I had copied wrong line, already I edited my last comment (:

**Comment by OscarHanzely** [comment]
I am getting this problem now on latest php-cs-fixer
Files that were not fixed due to errors reported during linting before fixing:
it is on any file that has the declaration

**Comment by SpacePossum** [comment]
Hi @OscarHanzely 

This type of error typically gets reported if there is a syntax-error within the file. Could you share the content (or minimal/abstract sample of it) on which this occurred? (We might going to need the PHP version and fixer version you use as well in order to help you out)

**Comment by OscarHanzely** [comment]
@SpacePossum 
PHP CS Fixer 2.12.1 Long Journey by Fabien Potencier and Dariusz Ruminski (beef6cb)
I also tried the php-cs-fixer v2.2.20

Code that works:
`class Oauth2AccessTokenDocument extends Documentable
{
    public function test()
    {
        return true;
    }
}`

code that breaks
`class Oauth2AccessTokenDocument extends Documentable
{
    public function test(): bool
    {
        return true;
    }
}`

with error:
Files that were not fixed due to errors reported during linting before fixing:

**Comment by OscarHanzely** [comment]
UPDATE: never mind. for some reason the Ubuntu version of php got switched as alternative to  php 5.6 even though I was using php7+ syntax. restarted the apache with proper command and it works now. Sorry to bug you. If anybody ends in same problem, just check your php version for linter.

**Comment by SpacePossum** [comment]
Hi @OscarHanzely 

Great to hear you got the issue resolved, I've had similar issues a few times with VM setups on Ubuntu so no worries :)
Thanks for reporting back!

**Comment by OscarHanzely** [comment]
ok, I removed and re-installed the php, cause the `a2endmo php 7.0` was enabled with newer evrsions and it probably picked wrong executable file.
now its resolved.
```
~$ php -v
PHP 7.2.7-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jun 22 2018 08:44:50) ( NTS )
```
**ALL GOOD NOW**

**Comment by SpacePossum** [comment]
awesome : D
