### ISSUE TITLE
php7.4 property type hint and class_attributes_separation

### ISSUE THREAD

**Issue by nepster-web** [FriendsOfPHP/PHP-CS-Fixer#4768]
#### The PHP version you are using (`$ php -v`):
=> 7.4

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.16.1

#### The command you use to run PHP CS Fixer:
=> `php vendor/bin/php-cs-fixer fix --diff --config=.php_cs.php`

#### The configuration file you are using, if any:
```php
declare(strict_types=1);

$finder = PhpCsFixer\Finder::create()
    ->exclude('public')
    ->exclude('resources')
    ->exclude('storage')
    ->exclude('vendor')
    ->in(__DIR__);

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2' => true,
        'blank_line_after_opening_tag' => true,
        'compact_nullable_typehint' => true,
        'declare_equal_normalize' => ['space' => 'none'],
        'function_typehint_space' => true,
        'new_with_braces' => true,
        'no_empty_statement' => true,
        'no_leading_import_slash' => true,
        'no_leading_namespace_whitespace' => true,
        'no_whitespace_in_blank_line' => true,
        'return_type_declaration' => ['space_before' => 'none'],
        'single_trait_insert_per_statement' => true,
        'no_empty_phpdoc' => true,
        'single_blank_line_before_namespace' => true,
        'array_syntax' => ['syntax' => 'short'],
        'ordered_imports' => ['sortAlgorithm' => 'length'],

        'class_attributes_separation' => [
            'elements' => [
                'const',
                'method',
                'property',
            ]
        ],

        'blank_line_before_statement' => [
            'statements' => [
                'return',
            ]
        ],
    ])
    ->setFinder($finder);
```
#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
    protected array $fillable = [
        'name',
        'email',
        'password',
    ];
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
    protected array

 $fillable = [
        'name',
        'email',
        'password',
    ];
```

 * with the changes you expected instead:
```php
    protected array $fillable = [
        'name',
        'email',
        'password',
    ];
```

**Comment by SpacePossum** [comment]
maybe this is the same as https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4764 ? can you try updating?

**Comment by nepster-web** [comment]
![изображение](https://user-images.githubusercontent.com/5681979/73350886-8d37e680-4296-11ea-8d3b-02563667df4b.png)

**Comment by julienfalque** [comment]
@nepster-web Can you try with the `dev` stability flag (e.g. `2.16.1@dev`)? The fix for #4764 is merged but not released yet.

**Comment by nepster-web** [comment]
hmm, without change.

![изображение](https://user-images.githubusercontent.com/5681979/73362223-207d1600-42af-11ea-8fa3-810d07fb1a34.png)

before:
![изображение](https://user-images.githubusercontent.com/5681979/73362292-44405c00-42af-11ea-8fd2-c06f0bcfc011.png)


after:
![изображение](https://user-images.githubusercontent.com/5681979/73362259-34287c80-42af-11ea-98d3-c29b6af45fbf.png)

**Comment by cv65kr** [comment]
This problem was resolved by adding `CT::T_ARRAY_TYPEHINT` in:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/5f240a335d0f62207a1e59cd7cc8048ba60b0be7/src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php#L233

This bug fix exists in branch `2.16` but is not released in `2.16.1`

**Comment by julienfalque** [comment]
Closing as the bug is already fixed.

**Comment by TomasVotruba** [comment]
When was it released? The bug still remains on v2.16.1

![image](https://user-images.githubusercontent.com/924196/76691059-ed1bfe00-6646-11ea-9e25-c2efa9eccb7e.png)

![image](https://user-images.githubusercontent.com/924196/76691066-f5743900-6646-11ea-8f63-9f80451fa8ba.png)

**Comment by SpacePossum** [comment]
fixed [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/fe3ead21102e76e5035e17bfe82f92ee7804325f#diff-aa9e97d556ec8c39613ee4d6251dea53 ) on Dec 1, 2019, 2.16.1 is from  Nov 25, 2019, so the fix is not released yet (sadly)

**Comment by TomasVotruba** [comment]
Why there is no releaes of bug that breaks the code for 6 months?

**Comment by SpacePossum** [comment]
I'd wish we had this bug release out sooner, I tried to make that happen but it didn't work

**Comment by TomasVotruba** [comment]
`git tag x` doesn't work? 

I have no idea why PHP CS Fixer development has stopped in last 6 months. Are there some health issues with maintainer?

**Comment by SpacePossum** [comment]
Development hasn't stopped, the releases are though. It is not as simple as the tagging, as we need to make a phar build as well and update the website and what not. This cannot be done by a lot of people.

**Comment by TomasVotruba** [comment]
It actually is that simple. Website and PHAR should be part of CI, independent on human, so it doesn't break peoeple's code. This is serious bus-factor problem that needs to be resolved. I believe this is not the last bug here.

**Comment by julienfalque** [comment]
@TomasVotruba Agreed, though using `2.16@dev` in the meantime is not a big deal. PRs to improve this are welcome I suppose.

**Comment by TomasVotruba** [comment]
It's not possible to install this package along 3rd party
