### ISSUE TITLE
Comment wrongly indented

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#5115]
CS fixer version: latest 2.16

Original code and expected result:
```
class CrudHelper
{
    public function makeCrudFromModel($model): MyCrud
    {
        // set model options
        if ($model instanceof Model\Invoice) {
            $model->getField($model->fieldName()->my_address_id)->default = 123456879;
            // @TODO
        } elseif ($model instanceof Model\InvoiceItem) {
            // @TODO
            $a = [
//                'test',
            ];
        }
// test
    }
}
```

badly fixed to:
```
class CrudHelper
{
    public function makeCrudFromModel($model): MyCrud
    {
        // set model options
        if ($model instanceof Model\Invoice) {
            $model->getField($model->fieldName()->my_address_id)->default = 123456879;
        // @TODO
        } elseif ($model instanceof Model\InvoiceItem) {
            // @TODO
            $a = [
                //                'test',
            ];
        }
// test
    }
}
```

there are two indent issues:
1. 4 spaces are removed badly for the first `// @TODO` comment - related with https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6490#issuecomment-1186203584
2. code commented with `//` right after a new line should never be moved, even if inside an array

config:
```
<?php

$finder = PhpCsFixer\Finder::create()
    ->in([__DIR__])
    ->exclude([
        'cache',
        'build',
        'vendor',
    ]);

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@PhpCsFixer' => true,
        '@PhpCsFixer:risky' =>true,
        '@PHP71Migration:risky' => true,
        '@PHP73Migration' => true,

        // required by PSR-12
        'concat_space' => [
            'spacing' => 'one',
        ],

        // disable some too strict rules
        'phpdoc_types' => [
            // keep enabled, but without "alias" group to not fix
            // "Callback" to "callback" in phpdoc
            'groups' => ['simple', 'meta']
        ],
        'phpdoc_types_order' => [
            'null_adjustment' => 'always_last',
            'sort_algorithm' => 'none',
        ],
        'single_line_throw' => false,
        'yoda_style' => [
            'equal' => false,
            'identical' => false,
        ],
        'native_function_invocation' => false,
        'non_printable_character' => [
            'use_escape_sequences_in_strings' => true,
        ],
        'void_return' => false,
        'combine_consecutive_issets' => false,
        'combine_consecutive_unsets' => false,
        'multiline_whitespace_before_semicolons' => false,
        'no_superfluous_elseif' => false,
        'ordered_class_elements' => false,
        'php_unit_internal_class' => false,
        'php_unit_test_case_static_method_calls' => [
            'call_type' => 'this',
        ],
        'php_unit_test_class_requires_covers' => false,
        'phpdoc_add_missing_param_annotation' => false,
        'return_assignment' => false,
        'comment_to_phpdoc' => false,
        'list_syntax' => ['syntax' => 'short'],
        'general_phpdoc_annotation_remove' => [
            'annotations' => ['author', 'copyright', 'throws'],
        ],
        'nullable_type_declaration_for_default_null_value' => [
            'use_nullable_type_declaration' => false,
        ],
    ])
    ->setFinder($finder)
    ->setCacheFile(__DIR__ . '/.php_cs.cache');
```

**Comment by quazardous** [comment]
`array_indentation` will indent comments inside arrays.

```php
        //         'strict_param' => true,
        'array_syntax' => ['syntax' => 'short'],
        'braces' => [
            'allow_single_line_closure' => true,
            'position_after_functions_and_oop_constructs' => 'next',
            'allow_single_line_anonymous_class_with_empty_body' => true,
        ],
```

Should add some config that leave all comments untouched.

```php
//         'strict_param' => true,
        'array_syntax' => ['syntax' => 'short'],
        'braces' => [
            'allow_single_line_closure' => true,
            'position_after_functions_and_oop_constructs' => 'next',
            'allow_single_line_anonymous_class_with_empty_body' => true,
        ],
```

**Comment by julienfalque** [comment]
Keeping commented-out code is a bad practice IMO. I don't want it to be supported by the tool.

**Comment by quazardous** [comment]
> Keeping commented-out code is a bad practice IMO. I don't want it to be supported by the tool.

But it's often the case in big real life config files. You make a change you comment the old values with a date. I don't say to activate it by default.

**Comment by julienfalque** [comment]
> I don't say to activate it by default.

The default value doesn't matter. If we want to have such option, we need to implement it and maintain it in time. I disagree we should work on that here. If really important, one can still fork the fixer and tweak it to their needs.

**Comment by quazardous** [comment]
It's the beauty of open source projects, we talk it and can do it if needed (or not).

But (better) ignoring parts of code is sometimes missing in CS Fixer IMO (like in es lint).

**Comment by quazardous** [comment]
I made noise, but still the indentation of comments in arrays is not consistent (?) with indentation in structure blocks.

```php
while (true) {
// comment not indented
    break;
}

$foo = [
    // comment indented
    'hello' => 'world',
];
```

**Comment by julienfalque** [comment]
This part should be fixed by #4884.

**Comment by mvorisek** [comment]
Still present with the latest master/https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/b23c1c7beddcb219f6f5ef0428f1c34940060e44 .

Line comments with zero indentation should never be fixed as there comments represent a commented out code which is much more visible/readable when unfixed.

**Comment by SpacePossum** [comment]
> Line comments with zero indentation should never be fixed as there comments represent a commented out code which is much more visible/readable when unfixed.

Or the comments do not represent code that is commented out (like your own provided example here `// test`) but are just improperly indented comments and therefore should be fixed by the rule.
I don't think we should support the case of improperly indented comment out code, I agree with Julien.
I think this issue can be closed.

**Comment by c33s** [comment]
@julienfalque can we rediscuss this? 

aren't there more usecases as "Keeping commented-out code" for allowing developers to configure the handling of comments?

for example i use tools like phpstan or php-coding-standard which allow us to ignore a line or the next line via comment. i prefer to have this comment sitting on the left as i don't "count" them to the code itself.

```php
<?php
    private function sendGenericMessage(string $message): void
    {
        $notification = (new Notification('error'))
            ->content($message)
            ->importance(Notification::IMPORTANCE_HIGH)
        ;

// @phpstan-ignore-next-line
        $recipients = $this->notifier->getAdminRecipients();
```

i would love to have a setting where i can define that comments which are on the start of a line are kept where they are.

as php-cs-fixer doesn't have a feature (yet) where i can ignore the next line the only way to allow this specific coding standard is to disable `statement_indentation` which is far worse than also allow developers to keep commented-out code (or in my case style my phpstan ignores)

what do you think? is this usecase relevant enough to rediscuss this?

**Comment by rudiedirkx** [comment]
I agree @c33s so I've made a pretty simple & maintainable PR #7963

**Comment by Wirone** [comment]
@c33s what advantage do these comments give? For me it looks disjointed. Also, I don't understand the "as i don't "count" them to the code itself" argument, because in my opinion even those technical comments are part of the code, since they define how the code should be handled by the tooling, hence they carry significant information. Why they should be shifted to the left?

**Comment by Wirone** [comment]
> in a development/research code commented code is very often present and should not be indented

But _why_? I totally don't get the reasoning. What's the advantage of non-indented code?

In this particular case I see it mostly as an IDE issue, which can't toggle comments with indentation in mind, but adds `//` at the beginning of the line. And since I am against keeping commented code in the project (Git is for that), I don't see a reason to support it in Fixer as a core rule/option.

**Comment by mvorisek** [comment]
In experimental code commented code is very usual even in the most professional teams. As such practise is normal in such usecase, the support should be present under harmless option.

**Comment by Wirone** [comment]
IMHO it would be a little like promoting messy code, which is against Fixer core concepts. If the IDE behaviour is a problem, and causes `statement_indentation` to indent such commented code (which is then left in weird state), then we should rather think how to achieve this:

```diff
 class Foo {
     public function bar()
     {
-//        if (true) {
-//            $a = 'b';
-//        }
+        // if (true) {
+        //     $a = 'b';
+        // }
     }
 }
```

IMHO we should add support for this in `single_line_comment_spacing`, that would make it possible to keep `statement_indentation` enabled, because the former has higher priority than the latter. The tricky part is maintaining code indentation within consecutive comments, but looking at `SingleLineCommentSpacingFixerTest` it seems like it's supported(?). Even if not, the code would be reformatted after uncommenting thanks to `statement_indentation`. Anyway, IMHO if the commented code has to be part of the repo, then it should be indented properly anyway. Maybe it should go to #7228 too.

Use cases like `// @phpstan-ignore-next-line` being disjointed from the annotated code are _not_ considered by me as something we should support.

**Comment by nbitouze** [comment]
I think @Wirone's solution offers a good compromise. I think most people who would prefer to preserve their
```diff
 class Foo {
     public function bar()
     {
//        if (true) {
//            $a = 'b';
//        }
     }
 }
```
rather that get the current "fix" behavior
```diff
 class Foo {
     public function bar()
     {
        //        if (true) {
        //            $a = 'b';
        //        }
     }
 }
```
would be very happy with the alternative fix of instead getting
```diff
 class Foo {
     public function bar()
     {
        // if (true) {
        //     $a = 'b';
        // }
     }
 }
```

Honestly, not only does it look like a good configuration option to add, it even looks like it should be the default. We're not talking about allowing poorly indented comments anymore (which, I agree, doesn't look like something phpcs should do), but we're talking about fixing them in a way that seems generally much better than what the current fix does.

**Comment by dmitryd** [comment]
I am sorry, but how can I turn it off and revent tp previous behavior? It now breaks our piplelines or we will have to reformat A LOT of code. Such changes should be conditional! There should be a way to keep comments unindented.

**Comment by rudiedirkx** [comment]
@Wirone @nbitouze #7963 does that. I use it locally with `cweagans/composer-patches` ❤️
